In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('creditcard.csv')

In [3]:
df.head(5)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [4]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [6]:
df['Class'].unique()

array([0, 1], dtype=int64)

In [7]:
df['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

In [9]:
df.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [10]:
legal=df[df['Class']==0]
fraud=df[df['Class']==1]

In [11]:
print(legal.shape,fraud.shape)

(284315, 31) (492, 31)

In [13]:
legal_samp=legal.sample(n=492) #no. of legal samples shud be same as fraudulant samples
legal_samp.shape

(492, 31)

In [18]:
legal_fraud=pd.concat([legal_samp,fraud],axis=0)
legal_fraud.shape
legal_fraud.head(5)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
40350,40204.0,-0.689644,0.299542,2.061807,0.925724,-0.279067,-0.871835,0.351762,-0.056058,-0.282939,...,-0.103556,-0.304241,0.176342,0.952172,-0.371685,0.350473,0.076589,0.141735,50.91,0
137920,82393.0,1.151572,0.290885,0.506260,1.156087,-0.293344,-0.615816,0.104389,-0.118605,-0.047784,...,0.132214,0.469458,-0.057353,0.418651,0.575664,-0.289512,0.037754,0.024620,14.90,0
122594,76619.0,-0.871046,-0.193232,1.469966,-2.202909,-1.184994,-1.334542,-0.486867,0.200785,-2.752837,...,-0.025868,0.038878,-0.053288,0.714038,0.022816,-0.373135,-0.018169,0.001881,20.14,0
166381,118043.0,-1.109345,1.052030,0.536907,-1.043013,-0.638257,-0.117692,-0.498068,1.028449,0.172713,...,-0.024442,-0.449201,0.036164,-0.521772,-0.230170,-0.279603,-0.497751,-0.129717,7.56,0
87893,61894.0,-0.365159,0.764418,-0.040896,-1.208815,2.440346,3.376401,0.139458,0.934943,-0.523820,...,-0.278836,-0.903970,-0.044798,0.982667,-0.033571,0.086240,0.265561,0.114540,7.99,0

In [20]:
legal_fraud['Class'].value_counts()

Class
0    492
1    492
Name: count, dtype: int64

In [21]:
# Scaling the data
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaled_data = scaler.fit_transform(legal_fraud.drop(columns='Class'))
scaled_legal_fraud_df = pd.DataFrame(scaled_data, columns=legal_fraud.columns[:-1])

In [22]:
scaled_legal_fraud_df.sample(5)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
913,1.210201,0.051466,0.214687,0.448886,-0.491304,0.467871,1.207079,0.182645,-1.369128,1.276000,...,-1.494023,2.097639,-1.084718,0.431957,-1.723043,0.310678,-0.746653,-0.067361,-0.198525,-0.376283
482,-0.628642,0.329225,-0.444355,0.897694,-0.911393,0.235320,0.010559,0.448559,-0.080780,-0.158396,...,0.046674,-0.103747,0.128463,0.053325,1.197349,-0.654257,-0.862238,-0.054111,0.213233,-0.368460
397,-0.430959,0.608015,-0.557785,0.677151,-0.472236,0.369263,1.136732,0.394188,0.033699,0.774991,...,-0.397187,-0.116250,0.443024,0.110107,-0.889556,0.296448,0.973318,-0.024270,-0.075331,-0.359424
18,-0.215195,0.476024,-0.255733,0.538261,-0.516766,0.660700,0.212286,0.679225,-0.147342,0.402564,...,0.054230,-0.125676,0.341010,-0.086132,-1.628598,-0.798862,-0.826203,0.179587,-0.087761,-0.313736
348,-1.166299,0.646326,-0.366641,0.510389,-0.436752,0.370786,-0.262203,0.518702,-0.094526,0.512467,...,-0.334055,-0.165537,-0.192462,0.032139,0.605209,0.637760,0.691766,-0.104706,0.000967,-0.404603

In [23]:
X = scaled_legal_fraud_df
y = legal_fraud['Class']

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, test_size=0.2)
print(X.shape, X_train.shape, X_test.shape)

(984, 30) (787, 30) (197, 30)

In [26]:
from sklearn.linear_model import LogisticRegression

In [27]:
model=LogisticRegression()

In [28]:
model.fit(X_train,y_train)

LogisticRegression()

In [29]:
model.predict(X_train)

array([1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0], dtype=int64)

In [30]:
from sklearn.metrics import accuracy_score

In [32]:
train_predict=model.predict(X_train)
test_predict=model.predict(X_test)

In [34]:
print("Training Data Accuracy: ",accuracy_score(train_predict, y_train))

Training Data Accuracy:  0.9453621346886912

In [35]:
print("testing Data Accuracy: ",accuracy_score(test_predict, y_test))

testing Data Accuracy:  0.9289340101522843